-- Supabase Setup Script for Large File Transfers
-- Run this in your Supabase SQL Editor.

-- 1. Create the database table for file transfer metadata
CREATE TABLE IF NOT EXISTS file_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename TEXT NOT NULL,
  size BIGINT NOT NULL,
  password_hash TEXT,
  encrypted_key TEXT,
  salt TEXT,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Safely add columns if the table already existed from a previous version
ALTER TABLE file_transfers ADD COLUMN IF NOT EXISTS encrypted_key TEXT;
ALTER TABLE file_transfers ADD COLUMN IF NOT EXISTS salt TEXT;

-- 2. Create the Storage Bucket
-- You can also do this from the UI: Create a PRIVATE bucket named 'transfers'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('transfers', 'transfers', false)
ON CONFLICT (id) DO NOTHING;

-- 3. Storage Security Policies
-- Since we are using Signed URLs generated by the Server (Service Role Key),
-- we DO NOT need to grant anonymous access to the storage bucket.
-- The bucket is completely locked down. Next.js API handles all secure access.

-- (Optional) Cron job or pg_cron to automatically delete expired transfers
-- You can enable this later if needed to keep storage costs down.
